version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: ~/foscam
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - deploy:
          name: Publish Library
          command: |
            deploy=$(git log -1 --pretty=%B | grep -o "^deploy([0-9]\+\.[0-9]\+\.[0-9]\+)")
            if [ $deploy ]
            then
              echo $deploy
              version=$(echo $deploy | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+")
              npm --no-git-tag-version version $version
              echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
              npm publish --access public
            fi
